project_id = "fagbmezuyjmvuhzelomu"

[functions.fetch-whatsapp-group-image]
verify_jwt = false

[functions.download-whatsapp-image]
verify_jwt = false

[functions.migrate-group-images]
verify_jwt = true